### PR TITLE
Debug logging

### LINKED ISSUE #322: Debug logging isn't persisted after a restart
**Describe the bug**
When the app is restarted it doesn't 

**To Reproduce**
1. turn on debug logging
2. restart app
3. see debug logging is turned off

**Expected behavior**
Debug logging should stay enabled

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jmbrunskill**
Fixes #322 

I couldn't figure out a good pattern for enabling it on start up.
After various different attempts I've put it into the DependancyContainer.
Probably not the right place but figure if it's working, it's better then nothing?

### CODE REVIEW

File: src/features/Bluetooth/Program/ProgramSlice.ts [hunk 1]
```diff
@@ -131,7 +131,9 @@ export function* tryProgramNewSensor({
     );
     ToastAndroid.show(`Connected and setup ${macAddress}`, ToastAndroid.SHORT);
   } catch (e) {
-    yield put(ProgramAction.programNewSensorFail(macAddress, e?.toString()));
+    yield put(
+      ProgramAction.programNewSensorFail(macAddress, e?.toString() ?? 'FAILED TO PROGRAM SENSOR')
```
Comment (jmbrunskill) [inline src/features/Bluetooth/Program/ProgramSlice.ts:135]: This is a side track but was giving be errors...

File: src/ui/containers/DependencyContainer.tsx [hunk 2]
```diff
@@ -123,6 +124,22 @@ export const DependencyContainer: FC = ({ children }) => {
     })();
   }, []);
 
+  useEffect(() => {
```
Comment (andreievg) [inline src/ui/containers/DependencyContainer.tsx:127]: Above we are settings ready = true and we have all of the services available (without query to DependencyLocator), I think we should move this logic there

**Comment by andreievg** [comment]
I would increase number of logs we keep: https://github.com/msupply-foundation/msupply-cold-chain/compare/Debug-Logging...Debug-Logging(Increase-number-of-logs-we-keep)

**Review by andreievg — APPROVED** [review]
Looks great thanks, just some suggestions.

I think we should [increase how much logs we are saving](https://github.com/msupply-foundation/msupply-cold-chain/blob/b2fd9920b19f18df2906ada39f290f9c69804e1b/.yalc/%40openmsupply/msupply-ble-service/src/Bluetooth/BleService.ts#L307), especially once below takes place

Also to solve this issue (in another PR): https://github.com/msupply-foundation/msupply-cold-chain/issues/318, I think we need some raw data from:

https://github.com/msupply-foundation/msupply-cold-chain/blob/b2fd9920b19f18df2906ada39f290f9c69804e1b/src/features/Bluetooth/Download/DownloadManager.ts#L94 <- log actual sensor logs we are saving

https://github.com/msupply-foundation/msupply-cold-chain/blob/b2fd9920b19f18df2906ada39f290f9c69804e1b/.yalc/%40openmsupply/msupply-ble-service/src/Bluetooth/BleService.ts#L307 <- log `data`, we could add automated test after that

I guess above would need to be under 'Debug' log levels ?

File: src/ui/containers/DependencyContainer.tsx (hunk 2 above)
Comment (jmbrunskill) [reply src/ui/containers/DependencyContainer.tsx]: Done [0db12fb](https://github.com/msupply-foundation/msupply-cold-chain/pull/323/commits/0db12fb0e923194181327b9b43684923664c858f)
