### PR TITLE
#294 fix empty cca app sync request

### LINKED ISSUE #294: CCA make a sync request when there is no records to be synced
**Describe the bug**
CCA app makes post/put requests regardless of having sync queue in the syncLog table records. Consequence is making the mSupply or omSupply server to have extra work load of process those incoming requests. Have seen in the Fiji moh server where most of their requests made from the CCA app had `body: "[]"`.

**To Reproduce**
1. Configure the CCA app to have interval or default interval >= 5mins
2. Configure sync store credentials to the mSupply or omSupply server
3. Wait for a delay interval to be ellapsed

**Expected behavior**
Should only make request when there is/are records in the sync queue (or `syncLog` table)

**Smartphone (please complete the following information):**

**Additional context**
```json
{"logType":"coldchain_request","logInfo":{"request":{"version":"HTTP/1.1","uri":"/coldchain/v1/sensor","method":"PUT","headers":{"Host":"__.msupply.org","User-Agent":"okhttp/3.12.12","Content-Length":"2","Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip","Content-Type":"application/json","Cookie":"coldchain=","X-Forwarded-For":"xx.xx.xx.xx","X-Forwarded-Host":"__.msupply.org","X-Forwarded-Proto":"https"},"routes":[],"cookies":{"coldchain":""},"body":"[]"},"response":{"status":200,"body":"{\"invalid\":[],\"valid\":[]}","headers":{"Content-Type":"application/json"}},"method":"AlternateHTTP_log","process":"AlternateHTTP_handler"},"timestamp":"2024-02-19T145448","sequenceNo":1498}
{"logType":"coldchain_request","logInfo":{"request":{"version":"HTTP/1.1","uri":"/coldchain/v1/sensor","method":"PUT","headers":{"Host":"__.msupply.org","User-Agent":"okhttp/3.12.12","Content-Length":"2","Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip","Content-Type":"application/json","Cookie":"coldchain=","X-Forwarded-For":"xx.xx.xx.xx","X-Forwarded-Host":"__.msupply.org","X-Forwarded-Proto":"https"},"routes":[],"cookies":{"coldchain":""},"body":"[]"},"response":{"status":200,"body":"{\"invalid\":[],\"valid\":[]}","headers":{"Content-Type":"application/json"}},"method":"AlternateHTTP_log","process":"AlternateHTTP_handler"},"timestamp":"2024-02-19T145449","sequenceNo":1499}
{"logType":"coldchain_request","logInfo":{"request":{"version":"HTTP/1.1","uri":"/coldchain/v1/temperature-breach","method":"PUT","headers":{"Host":"__.msupply.org","User-Agent":"okhttp/3.12.12","Content-Length":"2","Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip","Content-Type":"application/json","Cookie":"coldchain=","X-Forwarded-For":"xx.xx.xx.xx","X-Forwarded-Host":"__.msupply.org","X-Forwarded-Proto":"https"},"routes":[],"cookies":{"coldchain":""},"body":"[]"},"response":{"status":200,"body":"{\"invalid\":[],\"valid\":[]}","headers":{"Content-Type":"application/json"}},"method":"AlternateHTTP_log","process":"AlternateHTTP_handler"},"timestamp":"2024-02-19T145449","sequenceNo":1500}
```

### PR DESCRIPTION
**Pull request by raviSussol**
Fixes #294 

Makes requests for sensor, temparature log & temperature breach if there is/are data in the syncLog to be pushed.

### CODE REVIEW

File: src/features/Sync/SyncSlice.ts [hunk 1]
```diff
@@ -179,8 +180,14 @@ function* authenticate({
   payload: { loginUrl, username, password },
 }: PayloadAction<AuthenticateActionPayload>): SagaIterator {
   const syncOutManager: SyncOutManager = yield call(getDependency, 'syncOutManager');
+  const syncQueueManager: SyncQueueManager = yield call(getDependency, 'syncQueueManager');
 
   try {
+    const totalRecordsToSend: number = yield call(syncQueueManager.length);
+    if (totalRecordsToSend === 0) {
+      yield put(SyncAction.authenticateSuccess());
```
Comment (jmbrunskill) [inline src/features/Sync/SyncSlice.ts:188]: I don't like the idea of returning a success for authenticate when we haven't actually authenticated.

I don't think we need to filter out empty requests here do we since we'd doing it on the sensors, temperature_logs, and breaches?

**Review by jmbrunskill — COMMENTED** [review]
Looks good Ravi. Maybe just take out the code returning Success for Authenticate when we haven't actually authenticated successfully. 

I'm guessing it's to avoid logging in if there are no records to send?
If so I think that logic should be in `function* syncAll({ ... })` 
If there's nothing to sync, you could skip the `authenticate and other steps and just  `yield put(SyncAction.updateIsSyncing(false));`?

File: src/features/Sync/SyncSlice.ts (hunk 1 above)
Comment (raviSussol) [reply src/features/Sync/SyncSlice.ts:188]: > I don't think we need to filter out empty requests here do we since we'd doing it on the sensors, temperature_logs, and breaches?

Yea not specifically needed though this is just to synchronize api call with other CCA data post api (/sensors/temperature-logs, etc) calls so that the app only authenticates at the time of data posting.

**Comment by raviSussol** [comment]
>If so I think that logic should be in function* syncAll({ ... })
If there's nothing to sync, you could skip the authenticate and other steps and just  yield put(SyncAction.updateIsSyncing(false));`?

That wouldn't stop from making api call (other than authenticate) to the server if we just check `syncQueueManager.length` in the `syncAll` - have to individually check each type records (sensor, temperature-log & temperature-breach) to really make sure either of api call only be made if there is/are specific type of records in the `syncLog`. So thought better to check in their main functions.

332c60f should resolve it.

File: src/features/Sync/SyncSlice.ts (hunk 1 above)
Comment (raviSussol) [reply src/features/Sync/SyncSlice.ts]: >  I don't like the idea of returning a success for authenticate when we haven't actually authenticated.

Yeah make sense... df28183

**Review by jmbrunskill — APPROVED** [review]
Looks good thanks Ravi!

**Comment by raviSussol** [comment]
Thanks for reviewing @jmbrunskill!
