### PR TITLE
Test connection 

### LINKED ISSUE #305: Check Server URL is ColdChain API When Testing Connection
**Describe the bug**

When configuring the Server URL for CCA, you can enter the mSupply Dashboard URL as a valid URL.

When you 'Test Connection' the result is 'Connection Established' and you can 'Start Integration'.

You don't need credentials to get 'Connection Established' when using the Dashboard URL.

Using the mSupply API and TSPlus URL results in HTTP response 404.

**To Reproduce**

1. Enter a Server URL, using a dashboard URL
2. Click on 'Test Connection'
3. See 'Connection Established' when using no credentials

**Expected behavior**

Do not accept any URL unless it is the ColdChain API (or other accepted platforms?)

**Smartphone (please complete the following information):**

 - Device: Samsung Tab 7 & 8
 - OS: Android 12
 - Version: 0.5.6 & 0.5.7

**Additional context**

~

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #305 

The response format differs slightly between oms & ms. I've now checked for both response shapes and have given custom success messages for each:

connection-test-oms

connection-test-msupply

To test:
* Run mSupply and configure the alternative server url, and the store credentials for a store
* enter the server url+port into CCA and edit the username and password
* test connection
* enter an invalid url or username / password and retry
* Run open mSupply server and repeat

A test apk is [available here](https://drive.google.com/open?id=1wFZehlnRlAZbgAflxCDobQyvEWzrPIvy&usp=drive_fs)

### CODE REVIEW

File: src/features/Sync/SyncSlice.ts [hunk 1]
```diff
@@ -357,8 +366,12 @@ function* testConnectionFailure({
...
 }
 
-function* testConnectionSuccess(): SagaIterator {
-  ToastAndroid.show('Connection established!', ToastAndroid.SHORT);
+function* testConnectionSuccessV1(): SagaIterator {
+  ToastAndroid.show('Connection to mSupply established!', ToastAndroid.SHORT);
+}
+
+function* testConnectionSuccessV2(): SagaIterator {
+  ToastAndroid.show('Connection to Open mSupply established!', ToastAndroid.SHORT);
```
Comment (jmbrunskill) [inline src/features/Sync/SyncSlice.ts:374]: Nice touch!

**Review by jmbrunskill — APPROVED** [review]
Haven't tested but seems logical. Nice to have the mSupply vs Open mSupply logic.

Would be nice to have something more concrete to rely on and differenciate by.
Make can create an issue to return something more specific from OMS?

**Comment by mark-prins** [comment]
yes! that would be better. I'm not sure why I would have differed from the mSupply response shape either
